/**
 * Firestore Schema Definitions
 * 
 * This file contains TypeScript interfaces for all Firestore collections.
 * These types should match the actual Firestore document structure.
 */

import type { Timestamp } from 'firebase-admin/firestore';

/**
 * Collection: break_plans
 * 
 * Stores break plans generated for users.
 * When a user requests a break plan, multiple plans are generated and stored here.
 * The `chosen` field indicates which plan the user selected.
 */
export interface BreakPlanDocument {
  /** Document ID (UUID) */
  id: string;
  
  /** User who created this plan (Firebase Auth UID) */
  user_id: string;
  
  /** Plan title (generated by LLM) */
  title: string;
  
  /** Plan description (generated by LLM) */
  description: string;
  
  /** Duration in minutes */
  duration: number;
  
  /** Location with reverse geocoded address */
  location: {
    /** Reverse geocoded address */
    address: string;
    /** Coordinates */
    coordinates: {
      lat: number;
      lng: number;
    };
  };
  
  /** Plan type (breath, walk, etc.) - extensible enum */
  type: 'breath' | 'walk' | string;
  
  /** Original user feeling/state when plan was requested */
  feeling: string;
  
  /** True when user selects this plan */
  chosen: boolean;
  
  /** Order in which plans appear in frontend (0, 1, 2, ...) */
  order: number;
  
  /** When the plan was created */
  created_at: Timestamp;
  
  /** When the plan was last updated */
  updated_at: Timestamp;
}

/**
 * Collection: history
 * 
 * Stores completed break sessions.
 * Only plans with `chosen: true` from break_plans should create history entries.
 */
export interface HistoryDocument {
  /** Document ID (UUID) */
  id: string;
  
  /** User who completed this break (Firebase Auth UID) */
  user_id: string;
  
  /** Reference to the break_plan that was used */
  break_plan_id: string;
  
  /** Plan title (copied from plan for quick access) */
  title: string;
  
  /** Actual duration in minutes (may differ from plan) */
  duration: number;
  
  /** When the break session started */
  started_at: Timestamp;
  
  /** When the break session completed */
  completed_at: Timestamp | null;
  
  /** Status of the break session */
  status: 'completed' | 'cancelled' | 'in_progress';
  
  /** When the history entry was created */
  created_at: Timestamp;
}

/**
 * Collection: users
 * 
 * Stores user profile information.
 * This collection is synced with Firebase Auth.
 */
export interface UserDocument {
  /** Firebase Auth UID (same as document ID) */
  id: string;
  
  /** User email address */
  email: string;
  
  /** Display name (optional) */
  display_name?: string;
  
  /** Profile photo URL (optional) */
  photo_url?: string;
  
  /** When the user account was created */
  created_at: Timestamp;
  
  /** When the user profile was last updated */
  updated_at: Timestamp;
  
  /** When the user last logged in */
  last_login_at: Timestamp;
}

/**
 * Collection: voice_conversations
 * 
 * Stores voice session data and transcripts.
 * This is used by the voice service (Module 3).
 */
export interface VoiceConversationDocument {
  /** Document ID (UUID) */
  id: string;
  
  /** User who had this conversation (Firebase Auth UID) */
  user_id: string;
  
  /** WebSocket session identifier */
  session_id: string;
  
  /** When the conversation started */
  started_at: Timestamp;
  
  /** When the conversation ended (null if still active) */
  ended_at: Timestamp | null;
  
  /** LLM-generated summary of the conversation (optional) */
  summary?: string;
  
  /** Full conversation transcript (optional) */
  transcript?: string;
  
  /** When the conversation document was created */
  created_at: Timestamp;
}

/**
 * Collection names as constants for type safety
 */
export const COLLECTIONS = {
  BREAK_PLANS: 'break_plans',
  HISTORY: 'history',
  USERS: 'users',
  VOICE_CONVERSATIONS: 'voice_conversations'
} as const;

/**
 * Type helper to get document type from collection name
 */
export type DocumentType<T extends keyof typeof COLLECTIONS> =
  T extends 'break_plans' ? BreakPlanDocument :
  T extends 'history' ? HistoryDocument :
  T extends 'users' ? UserDocument :
  T extends 'voice_conversations' ? VoiceConversationDocument :
  never;


