#!/bin/bash

echo "📱 重置真机位置设置指南"
echo ""
echo "如果你的 iPhone 显示错误的位置（如旧金山而非真实位置），"
echo "请按以下步骤操作："
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "📍 步骤 1：检查模拟位置"
echo "   在 iPhone 上："
echo "   设置 → 隐私与安全性 → 定位服务"
echo "   → 滚动到底部查看是否有模拟位置"
echo "   → 如果有，关闭它"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "📍 步骤 2：重置应用权限"
echo "   在 iPhone 上："
echo "   设置 → 隐私与安全性 → 定位服务"
echo "   → 找到 'Take a Break' 或 'Expo Go'"
echo "   → 选择 '使用应用期间'"
echo "   → 确保 '精确位置' 开关打开"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "📍 步骤 3：重启应用"
echo "   1. 从后台完全关闭应用"
echo "   2. 重新打开应用"
echo "   3. 如果提示授权位置，选择 '允许'"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "📍 步骤 4：验证位置"
echo "   打开 iPhone 自带的 '地图' 应用"
echo "   点击定位按钮（右上角）"
echo "   → 应该显示你的真实位置（纽约长岛）"
echo "   → 如果地图也显示错误，说明是系统级问题"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "🔧 高级故障排除："
echo ""
echo "如果上述步骤都不工作："
echo ""
echo "1️⃣ 重启 iPhone"
echo "   长按电源键 → 滑动关机 → 重新开机"
echo ""
echo "2️⃣ 重置位置与隐私设置"
echo "   设置 → 通用 → 传输或还原 iPhone"
echo "   → 还原 → 还原位置与隐私"
echo "   ⚠️  这会重置所有应用的位置权限"
echo ""
echo "3️⃣ 检查日期和时区"
echo "   设置 → 通用 → 日期与时间"
echo "   → 确保 '自动设置' 打开"
echo ""
echo "4️⃣ 到户外测试"
echo "   GPS 在室内可能信号弱"
echo "   到窗边或户外等待 30 秒再测试"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "💡 调试提示："
echo ""
echo "在应用中查看完整的位置信息："
echo "打开应用后，在终端日志中查找："
echo ""
echo "  [MapService] Device location obtained: {...}"
echo ""
echo "如果显示："
echo "  • lat: 40.xxxx, lng: -73.xxxx → 正确（纽约）✅"
echo "  • lat: 37.xxxx, lng: -122.xxxx → 错误（旧金山）❌"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""



