name: Web Preview

on:
  push:
    branches:
      - main
    paths:
      - 'apps/web/**'
      - 'packages/break-plans/**'
      - 'package.json'
      - 'pnpm-lock.yaml'
  pull_request:
    paths:
      - 'apps/web/**'
      - 'packages/break-plans/**'
      - 'package.json'
      - 'pnpm-lock.yaml'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PNPM
        uses: pnpm/action-setup@v3
        with:
          version: 8

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Run unit tests
        run: pnpm test:web

      - name: Build web bundle
        run: pnpm build:web

      - name: Upload dist artifact
        uses: actions/upload-artifact@v4
        with:
          name: take-a-break-web
          path: apps/web/dist

